sudo: required
language: cpp
compiler:
    - gcc
script:
  - ./SetupLinux.sh
  - cd Test
  - ./runtests
before_install:
  # g++4.8.1
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - sudo apt-get update -qq
install:
  # g++4.8.1
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
deploy:
  provider: bintray
  file: "/home/travis/build/soma-arc/glslang/bintray.desc"
  user: "soma-arc"
  key: $BINTRAY_API_KEY
env:
  secure: "e6tM/bBj3PLIPTDpb0bDtEhinuS+vZGRcmqu1sM8MG6ZAWSPf0coj4gIX8VQl7tHt5WGNZOc4HBAHsyQL5Uay304VR2StnvtVCYPh1CVAphvzdelt9NQ7YHmlu2EMpvU/K8oKd8HRfMf1UyaFbTeXTUhT/mZ5qDI3ly/h3cCZO+zDAMwdFOzAxlp+x6mOcr6gGNaSdMHyi9i4u7kj5w9Ojta/5dBwkaLB/QO2jDJp+w23gcy6WILN8LpLz5K+vXvRcK5lvkTgnRbWsTxOYN0JKGb6GuSSZhOzx27MI+l7u8E5OMct0UbH2hQiLK9VM+n4xpPnuy+ltsfz+1/LNJpPmmY0eW1yZi5MEKyXCSIKL2epM7uBc1fPK05FM7bsKh01PPeVF8N+y0fKkEU+HQb8NuntTlDsdZgD/Ph39rJVwhzSlqo+5DJEJeNT3hdrPQ6E35sATnMf48pj/IpcGd8jh4vFivSbi8xkFTX6I8ivjCqtLojEn0Ehmy8qDnKBhBLxiC3K2vsNz03tqlOGQFKSGGoRDnMtnc6LBDxK4XHyOyBT99JQZ2ZAt35F+O8X4+J35et2m5fBH4eCZC8UiU6P8Dnc7/QFaXe3CXLK/58Hj9rd3e10moOTNz+svDT/362Mn6eiPw7RXeoUB95DMah4zjJlpFPXo5LN5bWJ5ohSo4="